### ISSUE TITLE
Tracking phase progress

### ISSUE THREAD

**Issue by takikawa** [WebAssembly/esm-integration#61]
This is a tracking issue for the phase requirements and other issues that should be resolved for the proposal.

**Phase 2 requirements**

* [X] Full proposed English spec text available in a forked repo around which a reasonably high level of consensus exists

**Phase 3 requirements**

* [X] Test suite has been updated to cover the feature in its forked repo
  - An initial test suite is in WPT now: https://github.com/web-platform-tests/wpt/tree/master/wasm/webapi
* [X] The test suite should run against some implementation, though it need not be the reference interpreter
  - Initial support is in WebKit: https://github.com/WebKit/WebKit/commit/9385643db6a368e05737c1e2a5240e7ad73c01e3

**Phase 4 Requirements**

* [ ] Two or more Web VMs implement the feature
  * [ ] V8 (tracking bug: https://bugs.chromium.org/p/chromium/issues/detail?id=841494)
  * [ ] Firefox

* [ ] At least one toolchain implements the feature

* [ ] The formalized spec is updated (N/A but HTML spec should be updated)

* [ ] Community Group has reached consensus in support of the feature

**Comment by guybedford** [comment]
There are requirements on the ESM integration implied by https://github.com/WebAssembly/component-model/pull/6. Will extending the ESM integration to support components be considered a follow-up proposal or part of this main ESM integration proposal?

**Comment by takikawa** [comment]
I agree, I think a follow-up proposal would make sense. Especially if it will rely on import reflection. I'll mention this topic at the CG meeting next week too.
